### ISSUE TITLE
Cast Exception

### ISSUE THREAD

**Issue by ltagliamonte** [inreachventures/aws-signing-request-interceptor#2]
Hi nice work!
i'm using your library to check and initialise an index on a ES and i'm having the following cast exception:

```
Caused by: java.lang.ClassCastException: org.apache.http.client.methods.HttpHead cannot be cast to org.apache.http.HttpEntityEnclosingRequest
	at vc.inreach.aws.request.AWSSigningRequestInterceptor.body(AWSSigningRequestInterceptor.java:59)
	at vc.inreach.aws.request.AWSSigningRequestInterceptor.process(AWSSigningRequestInterceptor.java:32)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:48)
	at com.draios.services.ElasticSearchService.initSchema(ElasticSearchService.java:99)
	at com.draios.services.ElasticSearchService.<init>(ElasticSearchService.java:77)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
```
here is the code:
```
private void initSchema(JestClient esClient, String esIndex, String esEndpoint) throws IOException {
        boolean indexExists = esClient.execute(new IndicesExists.Builder(esIndex).build()).isSucceeded();
        if (indexExists) {
            logger.info("Index {} is already configured on {}", esIndex,esEndpoint);
        }else {
            logger.info("Index {} is not configured on {} creating", esIndex,esEndpoint);
            esClient.execute(new CreateIndex.Builder(esIndex).build());
        }
    }
```
using my a local elasticsearch node as endpoint it is working properly.

**Comment by thesmith** [comment]
Thanks @ltagliamonte, I'll take a look.

**Comment by ltagliamonte** [comment]
Hi @thesmith any eta on working on it?
Thank in advance
L.

**Comment by thesmith** [comment]
Ha. Nope.

Feel free to provide a PR. I'll try and take a look when I can, but it's on a long list.

**Comment by thesmith** [comment]
I had a look and it was actually quite easy. Could you test against master / 0.0.5-SNAPSHOT?

**Comment by ltagliamonte** [comment]
@thesmith tested with 0.0.5-SNAPSHOT looking forward to 0.0.5 stable.
Regards
L.

**Comment by thesmith** [comment]
0.0.5 has been released. Enjoy and thanks!
